import pytest

from pipelex import pretty_print
from pipelex.cogt.img_gen.img_gen_job_factory import ImgGenJobFactory
from pipelex.hub import get_img_gen_worker
from tests.integration.pipelex.test_data import ImageGenTestCases


@pytest.mark.img_gen
@pytest.mark.inference
@pytest.mark.asyncio(loop_scope="class")
class TestImageGeneration:
    @pytest.mark.parametrize(("topic", "img_gen_prompt_text"), ImageGenTestCases.IMAGE_DESC)
    async def test_img_gen_using_handle(self, img_gen_handle: str, topic: str, img_gen_prompt_text: str):
        img_gen_worker_async = get_img_gen_worker(img_gen_handle=img_gen_handle)
        img_gen_job = ImgGenJobFactory.make_img_gen_job_from_prompt_contents(
            positive_text=img_gen_prompt_text,
        )
        generated_image = await img_gen_worker_async.gen_image(
            img_gen_job=img_gen_job,
        )
        pretty_print(generated_image, title=f"Image generated by '{img_gen_handle}' for topic '{topic}'")
