from typing import cast

import pytest

from pipelex import pretty_print
from pipelex.core.concepts.concept_native import NativeConceptEnum
from pipelex.core.pipes.pipe_run_params import PipeRunMode
from pipelex.core.pipes.pipe_run_params_factory import PipeRunParamsFactory
from pipelex.hub import get_pipe_router
from pipelex.pipe_operators.img_gen.pipe_img_gen import PipeImgGenOutput
from pipelex.pipe_operators.img_gen.pipe_img_gen_blueprint import PipeImgGenBlueprint
from pipelex.pipe_operators.img_gen.pipe_img_gen_factory import PipeImgGenFactory
from pipelex.pipe_works.pipe_job_factory import PipeJobFactory
from tests.integration.pipelex.test_data import ImageGenTestCases


@pytest.mark.dry_runnable
@pytest.mark.img_gen
@pytest.mark.inference
@pytest.mark.asyncio(loop_scope="class")
class TestPipeImgGen:
    @pytest.mark.parametrize("topic, image_desc", ImageGenTestCases.IMAGE_DESC)
    async def test_pipe_img_gen(
        self,
        pipe_run_mode: PipeRunMode,
        img_gen_handle: str,
        topic: str,
        image_desc: str,
    ):
        pipe_img_gen_blueprint = PipeImgGenBlueprint(
            definition="Image generation test",
            img_gen_prompt=image_desc,
            output=NativeConceptEnum.IMAGE,
            nb_output=1,
        )

        pipe_job = PipeJobFactory.make_pipe_job(
            pipe=PipeImgGenFactory.make_from_blueprint(
                domain="generic",
                pipe_code="adhoc_for_test_pipe_img_gen",
                blueprint=pipe_img_gen_blueprint,
            ),
            pipe_run_params=PipeRunParamsFactory.make_run_params(pipe_run_mode=pipe_run_mode),
        )
        pipe_img_gen_output = cast(
            PipeImgGenOutput,
            await get_pipe_router().run(
                pipe_job=pipe_job,
            ),
        )
        image_urls = pipe_img_gen_output.image_urls[0]
        pretty_print(image_urls, title=f"Image generated by '{img_gen_handle}' for topic '{topic}'")
